### ISSUE TITLE
Parameter settings for the algorithms in ensemble

### ISSUE THREAD

**Issue by ghost** [H00N24/PV056-AutoML-testing-framework#11]
Hi,
Is it possible to change parameter settings for the individual algorithm used in voting/stacking (weka.classifiers.meta.Vote/weka.classifiers.meta.Stacking) within this framework?

**Comment by H00N24** [comment]
Hi, maybe it would be possible, but could you please provide the whole Weka command for voting?
( `java -classpath weka.jar weka.classifiers.meta.FilteredClassifier -t "training.arff" ...`)

**Comment by ghost** [comment]
e.g. java -classpath weka.jar weka.classifiers.meta.Vote -t training.arff -B "weka.classifiers.rules.JRip -N 4" -B "weka.classifiers.rules.PART -C 0.5"

**Comment by H00N24** [comment]
FYI @NoName115

**Comment by NoName115** [comment]
@petrsha 
Hi I don't really see what is the problem, I wrote config file using command that you provided, e.g.
```
{
    "output_folder": "clf_outputs/",
    "weka_jar_path": "weka-3-8-3/weka.jar",
    "n_jobs": 5,
    "classifiers": [
        {
            "class_name": "weka.classifiers.meta.Vote",
            "args": [
                "-B",
                "weka.classifiers.rules.JRip -N 4",
                "-B",
                "weka.classifiers.rules.PART -C 0.5"
            ]
        }
    ]
}
```
And everything works just fine.

If you want to run 'Vote' classifier with different configuration, you just need to add that into configuration file, e.g.
```
{
    "output_folder": "clf_outputs/",
    "weka_jar_path": "weka-3-8-3/weka.jar",
    "n_jobs": 5,
    "classifiers": [
        {
            "class_name": "weka.classifiers.meta.Vote",
            "args": [
                "-B",
                "weka.classifiers.rules.JRip -N 4",
                "-B",
                "weka.classifiers.rules.PART -C 0.5"
            ]
        },
        {
            "class_name": "weka.classifiers.meta.Vote",
            "args": [
                "-B",
                "weka.classifiers.rules.JRip -N 20",
                "-B",
                "weka.classifiers.rules.PART -C 1"
            ]
        }
    ]
}
```

**Comment by ghost** [comment]
...I did this yesterday and it didn't work, but now it works...sorry for wasting your time.
