### ISSUE TITLE
Default classifier parameters

### ISSUE THREAD

**Issue by xkaple01** [H00N24/PV056-AutoML-testing-framework#12]
Hi,
If i understood correctly, in the last step we have to run 14 different classifiers with default parameter settings. But some classifiers (multilayer perceptrons and maybe some others) don't have default parameters. In order to run multilayer perceptron we have to explicitly specify the number of layers and units in layer. What should we do in such cases? Which classifier parameters  to use?

**Comment by H00N24** [comment]
Hi,
I would suggest you use the best configuration from the first part, however
questions about the task should be directed to the doc. Popelinský (popel@mail.muni.cz).

**Comment by xkaple01** [comment]
According to weka documentation, it seems all other 13 classifiers have all needed default parameters.  in case of perceptrons the following configuration can be used:

 "args":[
            "-H",
            "100",
            "-N",
            "100",
            "-L",
            "0.1",
            "-V",
            "20",
            "-E",
            "10"
        ]
