### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by postyear** [H00N24/PV056-AutoML-testing-framework#19]

**Comment by postyear** [comment]
I already know the KDN,CL,CLP etc, is from the paper titled **_An instance level analysis of data complexity___**; But i don't know **N1, N2, T1** who came up with it or what article it was in. Can you tell me where it's from？Thanks.

**Comment by H00N24** [comment]
Hi,

Unfortunately, I was not the one implementing these methods.

@xbazik00 @rastislavpapco @samuelmacko @halficek  guys do you know from which article are these methods?

**Comment by postyear** [comment]
> Hi,
> 
> Unfortunately, I was not the one implementing these methods.
> 
> @xbazik00 @rastislavpapco @samuelmacko @halficek guys do you know from which article are these methods?

I already found the source papaer, very appreciated.😀

**Comment by H00N24** [comment]
> I already found the source papaer, very appreciated.

Glad to hear that. Could you please post here the name if someone else would be looking for it? Thanks.

**Comment by postyear** [comment]
> > I already found the source papaer, very appreciated.
> 
> Glad to hear that. Could you please post here the name if someone else would be looking for it? Thanks.

OK，of course. The paper is:
Geometrical Complexity of Classification Problems. CoRR cs.CV/0402020 (2004)
