### ISSUE TITLE
pv056-enrich-data - ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by tomskypy** [H00N24/PV056-AutoML-testing-framework#6]
**Describe the bug**
"ModuleNotFoundError: No module named 'utils'" when running  "pv056-enrich-data".

**To Reproduce**
Try running (with the [latest master commit](https://github.com/H00N24/PV056-AutoML-testing-framework/commit/7c4db70f14c238bfab6437559bb09c22c75cfa1f) pulled) anything, e.g. "pv056-enrich-data --help" and you should see error traceback as follows:
"Traceback (most recent call last):
  File "/Users/.../venv/bin/pv056-enrich-data", line 11, in <module>
    load_entry_point('pv056-2019', 'console_scripts', 'pv056-enrich-data')()
...
File "/Users/.../ML/PV056-AutoML-testing-framework/pv056_2019/data_loader.py", line 14, in <module>
    from utils import ID_NAME
ModuleNotFoundError: No module named 'utils' "

**Desktop (please complete the following information):**
 - OS: macOS HS 10.13.4
 - App: Terminal, Version 2.8.2

**Comment by NoName115** [comment]
Fixed. Pull master.
